"""empty message

Revision ID: 833cab3f0e73
Revises: 
Create Date: 2024-09-12 16:55:36.156966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833cab3f0e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('web_id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('path', sa.String(length=150), nullable=False),
    sa.Column('descriptor', sa.String(length=150), nullable=True),
    sa.Column('point_class', sa.String(length=15), nullable=True),
    sa.Column('point_type', sa.String(length=15), nullable=True),
    sa.Column('digital_set_name', sa.String(length=150), nullable=True),
    sa.Column('engineering_units', sa.String(length=15), nullable=True),
    sa.Column('span', sa.Integer(), nullable=True),
    sa.Column('zero', sa.Integer(), nullable=True),
    sa.Column('step', sa.Boolean(), nullable=True),
    sa.Column('future', sa.Boolean(), nullable=True),
    sa.Column('display_digits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_tag')
    # ### end Alembic commands ###
